spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/runapp?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: 'update'

app:
  jwt:
    sign-key: mgs3AO0gExS8GLLwdOR74R1f8fwyBaGSsFjJ8GShwBEWA591LPy5fxAlHYox4wmV4x4N09lnw7VrVRIfwOe/JQ==